"use client";
import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";
import { ClerkProvider } from "@clerk/nextjs";
import { CartContext } from "./_context/CartContext";
import { useState } from "react";
import { ThemeProvider } from "./_components/theme-provider"

const inter = Roboto({ subsets: ["latin"], weight: ["500", "700", "900"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [cart, setCart] = useState([]);
  return (
    <ClerkProvider>
      <CartContext.Provider value={{ cart, setCart }}>
        <html lang="en">
          <body className={`${inter.className} bg-slate-200 dark:bg-main-color` }>
            <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
              <Header />
              {children}
              <Footer />
              </ThemeProvider>
          </body>
        </html>
      </CartContext.Provider>
    </ClerkProvider>
  );
}